# Generated by Django 2.1.2 on 2018-10-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
