# Generated by Django 2.1.2 on 2018-10-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usuario_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('postulante', 'Postulante'),)},
        ),
    ]
