# Generated by Django 2.1.2 on 2018-10-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181024_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('postulante', 'Ver registro para postular'),)},
        ),
    ]
