# Generated by Django 2.1.2 on 2018-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_mascotas_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='estado',
            field=models.CharField(choices=[('RESCATADO', 'rescatado'), ('DISPONIBLE', 'disponible'), ('ADOPTADO', 'adoptado')], default='RESCATADO', max_length=15),
        ),
    ]
