# Generated by Django 2.1.2 on 2018-10-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181024_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='estado',
            field=models.CharField(choices=[('RESCATADO', 'Rescatado'), ('DISPONIBLE', 'Disponible'), ('ADOPTADO', 'Adoptado')], default='RESCATADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='perro/%Y'),
        ),
    ]
