# Generated by Django 2.1.2 on 2018-10-24 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181024_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
