# Generated by Django 2.1.2 on 2018-10-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181024_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.CharField(choices=[('ARICA', 'Arica y Parinacota'), ('TARAPACA', 'Tarapacá'), ('ANTOFAGASTA', 'Antofagasta'), ('ATACAMA', 'Atacama'), ('COQUIMBO', 'Coquimbo'), ('VALPARAISO', 'Valparaíso'), ('RANCAGUA', 'Libertador Gral. Bernardo OHiggins'), ('MAULE', 'Maule'), ('BIOBIO', 'Bío Bío'), ('ARAUCANIA', 'Araucanía'), ('LOSRIOS', 'Los Ríos'), ('LOSLAGOS', 'Los Lagos'), ('AYSEN', 'Aysén del Gral. Carlos Ibáñez del Campo'), ('MAGALLANES', 'Magallanes y Antártica Chilena'), ('METROPOLITANA', 'Metropolitana de Santiago')], default='METROPOLITANA', max_length=40),
        ),
    ]
