# Generated by Django 2.1.2 on 2018-10-27 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20181026_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
