# Generated by Django 2.1.2 on 2018-10-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_usuario_nombre_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='perro/%Y'),
        ),
    ]
