# Generated by Django 2.1.2 on 2018-10-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_usuario_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
